name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      context:
        type: string
        default: "."
      tag: 
        type: string
      secret_name:
        type: string
      aws_region:
        type: string
        default: "ca-central-1"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS Credentials
        with: 
          aws-access-key-id: ${{secrets.GITHUBACTIONS_AWS_ACCESS_KEY}}
          aws-secret-access-key:  ${{secrets.GITHUBACTIONS_AWS_SECRET_ACCESS_KEY}}
          aws-region: ca-central-1

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: say8425/aws-secrets-manager-actions@v1
        with:
          AWS_ACCESS_KEY_ID: ${{secrets.GITHUBACTIONS_AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.GITHUBACTIONS_AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ca-central-1
          SECRET_NAME: ${{inputs.secret_name}}

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - uses: aws-actions/amazon-ecr-login@v1
        name: AWS ECR Login
        id: login-ecr

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: ${{inputs.context}}
          push: true
          tags: ${{inputs.image_name}}:${{inputs.tag}}


