name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: Name of the container image without a tag
        required: true
        type: string
      ecr_repo:
        description: Name of the Amazon Elastic Container Registry repo used to store container images
        required: true
        type: string
      context:
        type: string
        description: The context directory containing the Dockerfile
        default: "."
      dockerfile:
        type: string
        description: The name of the Dockerfile to build
        default: "Dockerfile"
      region:
        type: string
        description: The AWS region to use for deployment
        default: "ca-central-1"
      submodules:
        type: boolean 
        description: Whether to checkout Git submodules
        default: false
    secrets:
      aws_access_key_id:
        required: true
        description: The AWS access key ID with permissions to access the ECR repository
      aws_secret_access_key:
        required: true
        description: The AWS secret access key with permissions to access the ECR repository
      cicd_ssh_access_key:
        required: false
        description: The SSH access key for the CI/CD pipeline (if applicable)
      pac:
        required: false
        description: The personal access token for accessing Git submodules (if applicable)

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        if: false == ${{inputs.submodules}}
      
      - name: Checkout Code with Submodules
        uses: actions/checkout@v3
        if: ${{inputs.submodules}}
        with:
          submodules: 'recursive'
          token: ${{secrets.pac}}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.aws_access_key_id}}
          aws-secret-access-key:  ${{secrets.aws_secret_access_key}}
          aws-region: ${{inputs.region}}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Extract ticket from branch name
        id: extract_ticket
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          TICKET=$(echo $BRANCH_NAME | cut -d/ -f1)
          echo "::set-output name=ticket::$TICKET"


      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image_name}}
          tags: |
            type=raw,value=pr-${{ github.event.number }},enable=${{ github.event_name == 'pull_request' }}
            type=raw,value=${{ steps.extract_ticket.outputs.ticket }},enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,suffix=,format=short

      - name: Read Secrets from AWS Secrets Manager
        uses: say8425/aws-secrets-manager-actions@v2.2.1
        with:
          AWS_ACCESS_KEY_ID: ${{secrets.aws_access_key_id}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.aws_secret_access_key}}
          AWS_DEFAULT_REGION: ${{inputs.region}}
          SECRET_NAME: build/generic/npm_tokens
          OUTPUT_PATH: '.env'

      - name: Set Build Arguments
        id: build_arg_var
        run: |
          BUILD_ARGS=$(cat .env)
          echo "BUILD_ARGS<<EOF" >> $GITHUB_ENV
          echo "$BUILD_ARGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          pull: true
          context: ${{inputs.context}}
          file: ${{inputs.dockerfile}}
          platforms: linux/amd64
          build-args: ${{ env.BUILD_ARGS }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

