name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: Name of container image without a tag
        required: true
        type: string
      environment:
        description: Name of Environment
        required: false
        type: string
      ecr_repo:
        description: Name of ECR repo used to store container images
        required: true
        type: string
      context:
        description: Context for where the Dockerfile exists
        type: string
        default: "."
      dockerfile:
        description: Dockerfile name
        type: string
        default: "Dockerfile"
      secret_name:
        description: AWS Secret Manger Secret Name
        type: string
      region:
        type: string
        default: "ca-central-1"
      submodules:
        type: boolean
        default: false
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      cicd_ssh_access_key:
        required: false
      pac:
        required: false

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v5
        if: ${{ inputs.submodules == false }}

      - uses: actions/checkout@v5
        if: ${{inputs.submodules}}
        with:
          submodules: 'recursive'
          token: ${{secrets.pac}}

      - id: var_set_outputs
        name: Set output values
        run: |
          echo "github_sha_tag=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
          echo "github_head_ref=$(echo ${GITHUB_HEAD_REF} | awk -F '/' '{print $1}')" >> "$GITHUB_OUTPUT"
          echo "github_ref=${GITHUB_REF}" >> "$GITHUB_OUTPUT"
          echo "github_ref_name=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          echo "github_ref_type=${GITHUB_REF_TYPE}" >> "$GITHUB_OUTPUT"
          echo "github_repository=${GITHUB_REPOSITORY}" >> "$GITHUB_OUTPUT"

      - id: var_read_outputs
        name: Display output values
        run: |
          echo user_tag: ${{ steps.user_branch_tag.outputs.user_tag }}
          echo github_sha_tag: ${{ steps.var_set_outputs.outputs.github_sha_tag }}
          echo github_head_ref: ${{ steps.var_set_outputs.outputs.github_head_ref }}
          echo github_ref: ${{ steps.var_set_outputs.outputs.github_ref }}
          echo github_ref_name: ${{ steps.var_set_outputs.outputs.github_ref_name }}
          echo github_ref_type: ${{ steps.var_set_outputs.outputs.github_ref_type }}
          echo github_repository: ${{ steps.var_set_outputs.outputs.github_repository }}

      - id: short_sha
        name: Set short SHA
        run: |
          echo "tag=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
          
      - uses: webfactory/ssh-agent@v0.10.0
        with:
            ssh-private-key: ${{ secrets.cicd_ssh_access_key }}  
            
      - uses: aws-actions/configure-aws-credentials@v6
        name: Configure AWS Credentials
        with:
          aws-access-key-id: ${{secrets.aws_access_key_id}}
          aws-secret-access-key:  ${{secrets.aws_secret_access_key}}
          aws-region: ${{inputs.region}}

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v4

      - uses: aws-actions/amazon-ecr-login@v2
        name: AWS ECR Login
        id: login-ecr

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          push: true
          pull: true
          context: ${{inputs.context}}
          file: ${{inputs.dockerfile}}
          platforms: linux/amd64
          build-args: ENVIRONMENT=${{inputs.environment}}
          tags: ${{inputs.environment}}_${{ steps.short_sha.outputs.tag }}

      - name: Verify Image
        id: verify_image
        run: |
          set +e
          docker manifest inspect ${{ steps.login-ecr.outputs.registry }}/${{inputs.image_name}}:${{inputs.environment}}_${{ steps.short_sha.outputs.tag }} > /dev/null 2>&1
          echo "exists=$?" >> "$GITHUB_OUTPUT"
