name: Deploys MFE artifacts

on:
  workflow_call:
    inputs:
      service_name:
        description: Name of the service
        required: true
        type: string
      environment:
        description: Name of Environment
        required: true
        type: string
      region:
        type: string
        default: "ca-central-1"
      domain:
        description: domain name for s3 bucket naming
        required: false
        type: string
      tag:
        description: optional tag to deploy
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      pac:
        required: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.region }}

      - id: short_sha
        name: Set Short SHA as var output
        run: |
          echo "::set-output name=tag::`echo ${GITHUB_SHA} | cut -c1-8`"

      - name: Install AWS CLI Tools
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - id: deploy_s3_artifacts
        name: Deploy S3 artifacts with proper caching
        run: |
          # Define source and destination
          SRC_PATH="s3://micro-frontend-artifacts/${{ inputs.service_name }}/${{ inputs.environment }}/${{ steps.short_sha.outputs.tag }}"
          DEST_BUCKET="s3://${{ inputs.environment }}-${{ inputs.service_name }}${{ inputs.domain }}"

          echo "Syncing ROOT directory files with short TTL (30s)..."
          aws s3 sync $SRC_PATH $DEST_BUCKET \
            --exact-timestamps \
            --cache-control "public, max-age=30" \
            --metadata-directive REPLACE \
            --exclude "static/*"

          echo "Syncing /static directory with 2-week TTL (immutable)..."
          aws s3 sync $SRC_PATH/static $DEST_BUCKET/static \
            --delete \
            --cache-control "public, max-age=1209600, immutable" \
            --metadata-directive REPLACE

          echo "Deployment completed with caching policies applied."
